[tool.black]
multi-line-output = 3  # Многострочный вывод (3 - вертикально висячий) для совместимости с isort.

[tool.isort]
multi_line_output = 3  # Многострочный вывод (3 - вертикально висячий).
include_trailing_comma = true  # Включает конечную запятую перед скобками в многострочных импортах.
force_grid_wrap = 0  # Принудительное оборачивание импортов в таблицу.
use_parentheses = true  # Использует скобки вместо слеша для продолжения линии, превысившей лимит.
ensure_newline_before_comments = true  # вставляет пустую строку перед комментарием после импорта.
line_length = 88  # Максимальная длина линии импорта.

[tool.pytest.ini_options]
minversion = "6.2.5"   # Версия pytest, начиная с которой будет работать этот файл (лучше указывать версию, которая установлена у вас).
addopts = "--cov=app"  # Автоматически подтянет написанное тут к команде pytest при запуске в терминале.
testpaths = ["tests"]  # Путь до папки с тестами (в данном примере папка лежит в корне).

[tool.coverage.run]
branch = true  # Включает анализ покрытия по веткам, а не по стокам кода.
omit = [".venv/*", "tests/*"]  # Файлы, которые не должны быть в отчетности или изменяться.
 
[tool.coverage.report]
omit = [".venv/*", "tests/*"]  # Файлы, которые не должны быть в отчетности.